### ISSUE TITLE
Add row count to User Sessions screen

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-audit#13]
Having row count even when table doesn't have filter is a nice UI feature. It allows you to quickly see number of active sessions in your production environment (especially when there are hundreds of them).

![image](https://user-images.githubusercontent.com/6158807/99368802-09a6bf00-28d5-11eb-88a1-8d8cab949551.png)
![image](https://user-images.githubusercontent.com/6158807/99368857-1deabc00-28d5-11eb-9324-22af0ab2bb91.png)

**Comment by bulgakovea** [comment]
Added in Haulmont/jmix-ui#376
