### ISSUE TITLE
Modified attributes are not displayed

### ISSUE THREAD

**Issue by zhenyazb** [Haulmont/jmix-audit#16]
1. Create project
2. Add audit addon
3. Set up entity log for User entity
4. Create a new user
5. Open Entity Log browser, tab View
6. Select entity User and search entries for the entity
7. Click the appeared entry in the table
 
Expected result: information about created attributes appeares in the table
Actual result: the table is empty

![entitylog](https://user-images.githubusercontent.com/45868670/106759147-d2ca8480-664b-11eb-833d-fdc9f0946075.png)

**Comment by owlet1997** [comment]
1. create entity with attribute with boolean type
2. create an instance with attribute value = false
3. delete an instance
4. open Log entity, tab View  
5. select row in table with latest changes (creating and deleting this instance) in left table

AR: attribute with boolean type if right table is empty
![image](https://user-images.githubusercontent.com/45730069/107759421-b8766200-6d41-11eb-866c-8eb29b817d24.png)
![image](https://user-images.githubusercontent.com/45730069/107759451-c5935100-6d41-11eb-80f0-1e66e5b12337.png)

**Comment by owlet1997** [comment]
the problem was because default value of Boolean field is null, not false, if check and re-check checkbox, it works
