### ISSUE TITLE
Predefined roles

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-audit#18]
In CUBA we had one role for entity log:
![image](https://user-images.githubusercontent.com/6158807/108736675-41b04480-754b-11eb-9dda-f42f02cdb327.png)

We can create more roles to cover other screens.

**Comment by maistrenkoIulia** [comment]
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2838-211
IntelliJ version: IntelliJ IDEA 2021.1.1 (Community Edition)
![image](https://user-images.githubusercontent.com/66992566/117131929-2cf5f580-adb3-11eb-8491-7ef903c0e468.png)
TC: entity log>view
set User entity
Instance >...
AR: Access denied

**Comment by bulgakovea** [comment]
The mechanism of the _Instance_ field implies that the user has access to the browser of the selected _Entity_. You need to give access to the browser, to the entity itself and its fields (read-only will suffice). This should fix the problem.

**Comment by andreysubbotin** [comment]
@Enjua please change the notification message for the Instance field, make the message more detailed.

Something like this: 
if the user doesn't have the right to open the screen, says: Access denied for screen <screenName>. Add permissions to open screen <screenName> .
if the user doesn't have the right to read entity, says: Access denied for reading entity <enityName>. Add permissions to reading entity <entityName>.

**Comment by andreysubbotin** [comment]
Added `entity-log` resource role that allows configuring and viewing entity log for entities.  Allows access to Administration -> Entity log screen.

**Comment by maistrenkoIulia** [comment]
verified
