### ISSUE TITLE
Change text field of User in entity log to dropdown

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-audit#21]
run app>adminisration>entity log
ER:  User field should be dropdown list with options
AR: User in text field
![image](https://user-images.githubusercontent.com/66992566/109481815-aeb96200-7a96-11eb-8851-50e479ef63c5.png)

**Comment by andreysubbotin** [comment]
According to security changes in Jmix, user can be selected only by suggestion field component in UI.
