### ISSUE TITLE
Missed filter component in entity log screen

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-audit#22]
comparing to cuba platform,
![image](https://user-images.githubusercontent.com/66992566/109482850-f55b8c00-7a97-11eb-81d2-cc39010989ff.png)
filter component has been missed in jmix platform
![image](https://user-images.githubusercontent.com/66992566/109482947-0efcd380-7a98-11eb-811e-6e6914147fe4.png)

**Comment by DartVerder** [comment]
Filter was added, but the text box depends on the length of the attribute name
![image](https://user-images.githubusercontent.com/69783839/113977339-81a95d80-9853-11eb-9692-ae4735aa084c.png)

With a long attribute name, the user cannot see what is contained in the textbox and use the filter
