### ISSUE TITLE
No logs have been returned with Restore change type

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-audit#24]
Jmix Studio plugin version: 1.0.SNAPSHOT2581-202
IntelliJ version: IntelliJ IDEA 2020.3.2 (Community Edition)

TC: create entity vai browser>remove
via entity inspector restore
entity log>select corresponding entity type, set change type = Restore>search
ER: restored entities should be returned
AR: no  logs have been returned with Restore change type

**Comment by dtaimanov** [comment]
@maistrenkoIulia , cannot reproduce, please, check again.
