### ISSUE TITLE
Entity log doesn't return records filtered by user/entity

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-audit#29]
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2626-202
IntelliJ version: IntelliJ IDEA 2020.3.2 (Community Edition)

add audit component
create entity>screens
run app
by admin create entity
entity log>set user= admin, set entity>search
ER: record should be displayed
AR: no record 
the same in case filtering only by user ar only by entity

**Comment by bulgakovea** [comment]
Can not reproduce

**Comment by maistrenkoIulia** [comment]
invalid test case described.
need to create setup for entity> apply changes before creating entity via browser
