### ISSUE TITLE
Entity Snapshots

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-audit#3]
### Progress

2021-08-24: 100%

Parts of task:

- [x] Move the data model
- [x] Move all services
- [x] Move diff-viewer and rework it to screen API
- [x] Refactoring "difference" data model
- [x] To make storage mechanism more flexible.
- [x] Write tests
- [x] Code review

**Comment by a616101** [comment]
Hi, Is there an implementation plan?

**Comment by alexbudarov** [comment]
It would be ideal if we could also make storage mechanism to be flexible.
E.g. provide a "repository" class encapculating loading and saving logic.
Storing snapshots in one database table leads to huge table that is difficult to maintain (e.g. difficult to delete old unnecessary data).
In Sherlock we had to override some beans in order to be able to store snapshots in a partitioned table.

**Comment by plakhov** [comment]
For saving snapshots needed add the following code into the UI controller:
```
    @Autowired
    private EntitySnapshotManager entitySnapshotManager;

    @Subscribe
    public void onAfterCommitChanges(AfterCommitChangesEvent event) {
        entitySnapshotManager.createSnapshot(getEditedEntity(), getEditedEntityContainer().getFetchPlan());
    }
```

Viewing snapshots for arbitrary entities is possible using the io\jmix\auditui\screen\snapshot\snapshot-diff.xml fragment.
The snapshots should be loaded into the frame from the edit screen controller:
```
    @Autowired
    private SnapshotDiffViewer snapshotDiff;

    @Autowired
    private EntityStates entityStates;
    
    @Subscribe
    public void onBeforeShow(BeforeShowEvent event) {
        Object editedEntity = getEditedEntity();
        if (editedEntity != null && !entityStates.isNew(editedEntity)) {
            snapshotDiff.loadVersions(editedEntity);
        }
    }
```

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3462-211
IntelliJ version: IntelliJ IDEA 2021.1.3 (Community Edition)
