### ISSUE TITLE
Delete generic filter from the Entity log screen

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-audit#35]
![image](https://user-images.githubusercontent.com/6158807/116373853-cdca3b00-a81e-11eb-9191-eee73cf4fb3e.png)

Second filter looks unnecessary.
Filter using simple fields covers almost all cases.

In case a project needs some custom field to filter by, one can extend the screen in their own project and add own conditions.
Or implement own browse screen from scratch - the "View" part is simple (e.g. like it is done in Sherlock).

**Comment by andreysubbotin** [comment]
The opposite issue: https://github.com/Haulmont/jmix-audit/issues/22. It looks like we are doing useless work. 
Original CUBA issue: https://youtrack.haulmont.com/issue/CUBA-10429

**Comment by maistrenkoIulia** [comment]
verified
