### ISSUE TITLE
Modify events are not tracked for entity from additional data store

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-audit#38]
Jmix version: 1.1 snapshot.

1) Install and restore dvdrental sample Postgres database:  https://www.postgresqltutorial.com/postgresql-sample-database/

2) Open the attached project.
[jdvd1.zip](https://github.com/Haulmont/jmix-audit/files/7366916/jdvd1.zip)

3) Point additional datastore "dvds" to the dvdrental database.
![image](https://user-images.githubusercontent.com/6158807/137768930-37a2392b-aae7-4345-b045-20e9b388bb04.png)

4) Launch application

5) Open Entity Log screen. Setup full entity logging for the "Language" entity.
![image](https://user-images.githubusercontent.com/6158807/137769132-2d7dbd3f-00c3-45ce-bd84-c7760a616c8f.png)

6) Open Languages screen. Create new language. Then edit (change caption). Then remove it.

7) Open Entity Log view tab.

Expected: 3 events (create, edit, remove)

Actual: only 2 events: create and remove.
![image](https://user-images.githubusercontent.com/6158807/137769174-4c529f8b-18fd-4221-8ded-77fc5e4c25bc.png)

**Comment by reznikova21** [comment]
1.2.0-SNAPSHOT - verified
