### ISSUE TITLE
Entity snapshot mechanism does not show diffs for one-to-many associations (port to 1.1)

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-audit#41]
### Description
See original: https://github.com/Haulmont/jmix-audit/issues/40

**Comment by konyashkina** [comment]
_Tested on_
Jmix version: 1.1.999-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3777-212
IntelliJ version: IntelliJ IDEA 2021.2.2 (Ultimate Edition)
