### ISSUE TITLE
Incorrect localization keys in messages for SnapshotDiffViewer fragment

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-audit#42]
### Description
1. Download demo project: [demo.zip](https://github.com/Haulmont/jmix-audit/files/7561140/demo.zip)
 
2. Open _Sandbox -> Order snapshots_

**AR**
![image](https://user-images.githubusercontent.com/22093943/142376636-526f8e21-ce0b-4b33-9338-1ff4ad8e598e.png)

**Comment by reznikova21** [comment]
1.2.0-SNAPSHOT - verified
